// lib/mockApiService.ts
import { LenderProfile } from '../types/lender';

export const getLenders = async (): Promise<LenderProfile[]> => {
  const mockLenders: LenderProfile[] = [
    {
      lender_id: 1,
      name: "National Commercial Lending",
      asset_types: ["Multifamily", "Office", "Retail"],
      deal_types: ["Acquisition", "Refinance"],
      capital_types: ["Senior Debt"],
      min_deal_size: 2000000,
      max_deal_size: 50000000,
      locations: ["National"],
      preference_scope: { asset_types: 0.8, deal_types: 0.7, capital_types: 0.9, locations: 0.5, deal_size: 0.7 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 2,
      name: "Regional Property Finance - Northeast",
      asset_types: ["Multifamily", "Industrial"],
      deal_types: ["Acquisition", "Construction"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 1000000,
      max_deal_size: 25000000,
      locations: ["Northeast", "Mid-Atlantic"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.8, locations: 0.9, deal_size: 0.8 },
      match_score: 0.85,
      debt_ranges: ["$5M - $25M"],
    },
    {
      lender_id: 3,
      name: "Sunbelt Development Fund",
      asset_types: ["Land", "Multifamily", "Industrial", "Hospitality"],
      deal_types: ["Development", "Construction", "Acquisition"],
      capital_types: ["Mezzanine", "Preferred Equity", "Equity"],
      min_deal_size: 5000000,
      max_deal_size: 100000000,
      locations: ["Southeast", "Southwest", "Sun Belt"],
      preference_scope: { asset_types: 0.8, deal_types: 0.9, capital_types: 0.9, locations: 0.8, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 4,
      name: "West Coast Realty Capital",
      asset_types: ["Office", "Retail", "Industrial", "Multifamily", "Medical Office"],
      deal_types: ["Refinance", "Acquisition", "Value-Add"],
      capital_types: ["Senior Debt"],
      min_deal_size: 3000000,
      max_deal_size: 75000000,
      locations: ["West Coast", "Pacific Northwest", "California"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.9, locations: 0.9, deal_size: 0.7 },
      match_score: 0.85,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 5,
      name: "Midwest Commercial Mortgage Trust",
      asset_types: ["Multifamily", "Industrial", "Self-Storage"],
      deal_types: ["Acquisition", "Refinance", "Bridge"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 1500000,
      max_deal_size: 40000000,
      locations: ["Midwest", "Southeast"],
      preference_scope: { asset_types: 0.8, deal_types: 0.8, capital_types: 0.8, locations: 0.7, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 6,
      name: "Atlantic Bridge Lending",
      asset_types: ["Hospitality", "Retail"],
      deal_types: ["Bridge", "Acquisition"],
      capital_types: ["Senior Debt"],
      min_deal_size: 5000000,
      max_deal_size: 60000000,
      locations: ["Northeast", "Southeast"],
      preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.8, deal_size: 0.7 },
      match_score: 0.75,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 7,
      name: "Pacific Equity Partners",
      asset_types: ["Office", "Retail", "Mixed-Use"],
      deal_types: ["Acquisition", "Value-Add"],
      capital_types: ["Preferred Equity", "Equity"],
      min_deal_size: 10000000,
      max_deal_size: 150000000,
      locations: ["West Coast"],
      preference_scope: { asset_types: 0.8, deal_types: 0.7, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
      match_score: 0.85,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 8,
      name: "Southern Capital Solutions",
      asset_types: ["Multifamily", "Student Housing"],
      deal_types: ["Development", "Acquisition"],
      capital_types: ["Construction", "Equity"],
      min_deal_size: 20000000,
      max_deal_size: 200000000,
      locations: ["Southeast", "Sun Belt"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.8, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 9,
      name: "Northern Industrial Finance",
      asset_types: ["Industrial", "Self-Storage", "Data Center"],
      deal_types: ["Acquisition", "Refinance"],
      capital_types: ["Senior Debt"],
      min_deal_size: 1000000,
      max_deal_size: 30000000,
      locations: ["Northeast", "Midwest"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.9, locations: 0.8, deal_size: 0.7 },
      match_score: 0.85,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 10,
      name: "Central States Lending Group",
      asset_types: ["Retail", "Mixed-Use"],
      deal_types: ["Acquisition", "Repositioning"],
      capital_types: ["Mezzanine", "Preferred Equity"],
      min_deal_size: 5000000,
      max_deal_size: 75000000,
      locations: ["Midwest", "Southwest"],
      preference_scope: { asset_types: 0.8, deal_types: 0.8, capital_types: 0.8, locations: 0.7, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 11,
      name: "Coastal Hospitality Funding",
      asset_types: ["Hospitality", "Mixed-Use"],
      deal_types: ["Construction", "Bridge"],
      capital_types: ["Senior Debt"],
      min_deal_size: 8000000,
      max_deal_size: 90000000,
      locations: ["West Coast", "Southeast"],
      preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.8, deal_size: 0.7 },
      match_score: 0.75,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 12,
      name: "Mountain View Capital",
      asset_types: ["Office", "Medical Office"],
      deal_types: ["Refinance", "Value-Add"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 2500000,
      max_deal_size: 60000000,
      locations: ["Mountain West", "West Coast"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.8 },
      match_score: 0.85,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 13,
      name: "Prairie Land Mortgage",
      asset_types: ["Land", "Industrial", "Agricultural"],
      deal_types: ["Development", "Acquisition"],
      capital_types: ["Equity"],
      min_deal_size: 15000000,
      max_deal_size: 150000000,
      locations: ["Midwest", "Southwest"],
      preference_scope: { asset_types: 0.8, deal_types: 0.8, capital_types: 0.9, locations: 0.8, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 14,
      name: "Great Lakes Finance Corp",
      asset_types: ["Multifamily", "Retail"],
      deal_types: ["Acquisition", "Repositioning"],
      capital_types: ["Preferred Equity"],
      min_deal_size: 7000000,
      max_deal_size: 80000000,
      locations: ["Midwest", "Northeast"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.8, deal_size: 0.7 },
      match_score: 0.85,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 15,
      name: "Sunshine State Lending",
      asset_types: ["Hospitality", "Senior Housing"],
      deal_types: ["Bridge", "Refinance"],
      capital_types: ["Senior Debt"],
      min_deal_size: 6000000,
      max_deal_size: 70000000,
      locations: ["Southeast", "Sun Belt"],
      preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
      match_score: 0.9,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 16,
      name: "Empire State Capital",
      asset_types: ["Office", "Retail", "Multifamily"],
      deal_types: ["Acquisition", "Value-Add"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 4000000,
      max_deal_size: 90000000,
      locations: ["Northeast", "Tri-State Area"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.7 },
      match_score: 0.85,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 17,
      name: "Golden Gate Funding",
      asset_types: ["Industrial", "Data Center"],
      deal_types: ["Refinance", "Development"],
      capital_types: ["Equity"],
      min_deal_size: 12000000,
      max_deal_size: 120000000,
      locations: ["West Coast", "Pacific Northwest"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 18,
      name: "Lone Star Mortgage Group",
      asset_types: ["Retail", "Hospitality"],
      deal_types: ["Acquisition", "Bridge"],
      capital_types: ["Preferred Equity"],
      min_deal_size: 9000000,
      max_deal_size: 100000000,
      locations: ["Southwest", "Southeast", "Sun Belt"],
      preference_scope: { asset_types: 0.8, deal_types: 0.9, capital_types: 0.8, locations: 0.8, deal_size: 0.8 },
      match_score: 0.85,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 19,
      name: "Windy City Lending Partners",
      asset_types: ["Multifamily", "Mixed-Use"],
      deal_types: ["Acquisition", "Repositioning"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 3500000,
      max_deal_size: 80000000,
      locations: ["Midwest", "Northeast"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.8, deal_size: 0.7 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 20,
      name: "Rocky Mountain Capital Trust",
      asset_types: ["Office", "Medical Office", "Senior Housing"],
      deal_types: ["Refinance", "Value-Add"],
      capital_types: ["Preferred Equity", "Equity"],
      min_deal_size: 11000000,
      max_deal_size: 110000000,
      locations: ["Mountain West", "Southwest"],
      preference_scope: { asset_types: 0.8, deal_types: 0.7, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 21,
      name: "Metroplex Commercial Finance",
      asset_types: ["Retail", "Mixed-Use"],
      deal_types: ["Acquisition", "Repositioning"],
      capital_types: ["Mezzanine", "Preferred Equity"],
      min_deal_size: 5000000,
      max_deal_size: 75000000,
      locations: ["Midwest", "Southwest"],
      preference_scope: { asset_types: 0.8, deal_types: 0.8, capital_types: 0.8, locations: 0.7, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 22,
      name: "New England Property Loans",
      asset_types: ["Hospitality", "Mixed-Use", "Retail"],
      deal_types: ["Bridge", "Refinance"],
      capital_types: ["Mezzanine"],
      min_deal_size: 7500000,
      max_deal_size: 85000000,
      locations: ["Northeast", "New England"],
      preference_scope: { asset_types: 0.8, deal_types: 0.9, capital_types: 0.8, locations: 0.9, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 23,
      name: "Great Plains Capital Group",
      asset_types: ["Land", "Agricultural", "Industrial"],
      deal_types: ["Development", "Acquisition"],
      capital_types: ["Equity"],
      min_deal_size: 16000000,
      max_deal_size: 160000000,
      locations: ["Midwest", "Mountain West"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.8, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 24,
      name: "Chesapeake Bay Lending",
      asset_types: ["Multifamily", "Office", "Retail"],
      deal_types: ["Acquisition", "Repositioning"],
      capital_types: ["Preferred Equity"],
      min_deal_size: 8500000,
      max_deal_size: 95000000,
      locations: ["Mid-Atlantic", "Southeast"],
      preference_scope: { asset_types: 0.8, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.7 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 25,
      name: "Evergreen State Finance",
      asset_types: ["Multifamily", "Student Housing"],
      deal_types: ["Development", "Acquisition"],
      capital_types: ["Construction", "Equity"],
      min_deal_size: 15000000,
      max_deal_size: 150000000,
      locations: ["Southeast", "Sun Belt"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.8, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 26,
      name: "Silicon Valley Capital Partners",
      asset_types: ["Office", "Data Center", "Life Science"],
      deal_types: ["Acquisition", "Value-Add", "Development"],
      capital_types: ["Equity", "Preferred Equity"],
      min_deal_size: 15000000,
      max_deal_size: 200000000,
      locations: ["West Coast", "Pacific Northwest"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 27,
      name: "Arizona Desert Funding",
      asset_types: ["Retail", "Hospitality"],
      deal_types: ["Acquisition", "Bridge"],
      capital_types: ["Senior Debt"],
      min_deal_size: 10000000,
      max_deal_size: 100000000,
      locations: ["Northeast", "Southeast"],
      preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.8, deal_size: 0.7 },
      match_score: 0.75,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 28,
      name: "Michigan Lakeshore Lending",
      asset_types: ["Multifamily", "Industrial", "Self-Storage"],
      deal_types: ["Acquisition", "Refinance", "Bridge"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 4500000,
      max_deal_size: 85000000,
      locations: ["Midwest", "Northeast", "Great Lakes"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.7 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 29,
      name: "Nashville Music City Lending",
      asset_types: ["Hospitality", "Senior Housing"],
      deal_types: ["Bridge", "Refinance"],
      capital_types: ["Senior Debt"],
      min_deal_size: 8500000,
      max_deal_size: 105000000,
      locations: ["Southeast", "Tennessee", "Sun Belt", "Urban"],
      preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$100M+"],
    },
    // ... (continue similarly for lenders 30 through 50; below are abbreviated examples)
    {
      lender_id: 30,
      name: "Texas Star Finance",
      asset_types: ["Industrial", "Data Center", "Self-Storage"],
      deal_types: ["Development", "Acquisition", "Refinance"],
      capital_types: ["Equity", "Senior Debt"],
      min_deal_size: 18000000,
      max_deal_size: 220000000,
      locations: ["Southwest", "Texas", "Sun Belt"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 31,
      name: "New York City Funding Group",
      asset_types: ["Multifamily", "Office", "Retail", "Mixed-Use"],
      deal_types: ["Acquisition", "Refinance", "Value-Add"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 5000000,
      max_deal_size: 100000000,
      locations: ["Northeast", "Tri-State Area", "Urban"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.7 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 32,
      name: "Los Angeles Property Lending",
      asset_types: ["Hospitality", "Retail", "Office", "Medical Office"],
      deal_types: ["Bridge", "Acquisition", "Repositioning"],
      capital_types: ["Preferred Equity", "Equity"],
      min_deal_size: 15000000,
      max_deal_size: 150000000,
      locations: ["West Coast", "California", "Urban"],
      preference_scope: { asset_types: 0.8, deal_types: 0.9, capital_types: 0.8, locations: 0.9, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$100M+"],
    },
    {
      lender_id: 33,
      name: "Chicago Commercial Capital",
      asset_types: ["Industrial", "Data Center", "Multifamily", "Mixed-Use"],
      deal_types: ["Development", "Refinance", "Acquisition"],
      capital_types: ["Equity", "Senior Debt"],
      min_deal_size: 20000000,
      max_deal_size: 250000000,
      locations: ["Midwest", "Illinois", "Urban"],
      preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
      match_score: 0.9,
      debt_ranges: ["$100M+"],
    },
    // ... Add lenders 34 to 50 in a similar fashion, ensuring each has a valid debt_ranges property.
    // For brevity, here's an abbreviated version for the remaining lenders:
    {
      lender_id: 34,
      name: "Houston Energy Corridor Lending",
      asset_types: ["Office", "Retail", "Industrial", "Mixed-Use"],
      deal_types: ["Refinance", "Value-Add", "Repositioning"],
      capital_types: ["Senior Debt", "Mezzanine"],
      min_deal_size: 7500000,
      max_deal_size: 85000000,
      locations: ["Southwest", "Texas", "Sun Belt", "Urban"],
      preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.7 },
      match_score: 0.8,
      debt_ranges: ["$25M - $100M"],
    },
    {
      lender_id: 35,
      name: "Nashville Music City Lending",
      asset_types: ["Hospitality", "Senior Housing"],
      deal_types: ["Bridge", "Refinance"],
      capital_types: ["Senior Debt"],
      min_deal_size: 8500000,
      max_deal_size: 105000000,
      locations: ["Southeast", "Tennessee", "Sun Belt", "Urban"],
      preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
      match_score: 0.8,
      debt_ranges: ["$100M+"],
    },
    {
        lender_id: 36,
        name: "Seattle Skyline Capital",
        asset_types: ["Office", "Medical Office", "Data Center", "Life Science"],
        deal_types: ["Refinance", "Acquisition", "Development"],
        capital_types: ["Preferred Equity", "Equity"],
        min_deal_size: 13000000,
        max_deal_size: 130000000,
        locations: ["Pacific Northwest", "Washington", "West Coast", "Urban"],
        preference_scope: { asset_types: 0.8, deal_types: 0.7, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
      },
      {
        lender_id: 37,
        name: "Denver Mile High Capital",
        asset_types: ["Office", "Medical Office", "Senior Housing", "Multifamily"],
        deal_types: ["Refinance", "Value-Add", "Acquisition"],
        capital_types: ["Preferred Equity", "Equity"],
        min_deal_size: 14000000,
        max_deal_size: 140000000,
        locations: ["Mountain West", "Colorado", "Southwest", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
      },
      {
        lender_id: 38,
        name: "Boston Harbor Lending",
        asset_types: ["Industrial", "Data Center", "Life Science", "Office"],
        deal_types: ["Development", "Refinance", "Value-Add"],
        capital_types: ["Equity", "Senior Debt"],
        min_deal_size: 22000000,
        max_deal_size: 280000000,
        locations: ["New England", "Massachusetts", "Northeast", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
        match_score: 0.9,
        debt_ranges: ["$100M+"],
      },
      {
        lender_id: 39,
        name: "Dallas Skyline Capital",
        asset_types: ["Industrial", "Self-Storage", "Retail", "Multifamily"],
        deal_types: ["Development", "Acquisition", "Bridge"],
        capital_types: ["Equity", "Senior Debt"],
        min_deal_size: 21000000,
        max_deal_size: 260000000,
        locations: ["Southwest", "Texas", "Sun Belt", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
        match_score: 0.9,
        debt_ranges: ["$100M+"],
      },
      {
        lender_id: 40,
        name: "San Diego Bay Funding",
        asset_types: ["Office", "Medical Office", "Life Science", "Data Center"],
        deal_types: ["Refinance", "Acquisition", "Value-Add"],
        capital_types: ["Preferred Equity", "Equity"],
        min_deal_size: 16000000,
        max_deal_size: 180000000,
        locations: ["West Coast", "California", "Pacific Northwest", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$100M+"],
      },
      {
        lender_id: 41,
        name: "Washington DC Metro Funding",
        asset_types: ["Retail", "Multifamily", "Office", "Medical Office"],
        deal_types: ["Acquisition", "Repositioning", "Bridge"],
        capital_types: ["Preferred Equity", "Equity"],
        min_deal_size: 14500000,
        max_deal_size: 135000000,
        locations: ["Mid-Atlantic", "Washington DC", "Northeast", "Urban"],
        preference_scope: { asset_types: 0.8, deal_types: 0.9, capital_types: 0.8, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
      },
      {
        lender_id: 42,
        name: "Minneapolis Twin Cities Capital",
        asset_types: ["Hospitality", "Senior Housing", "Multifamily", "Office"],
        deal_types: ["Bridge", "Value-Add", "Refinance"],
        capital_types: ["Senior Debt", "Mezzanine"],
        min_deal_size: 8000000,
        max_deal_size: 95000000,
        locations: ["Midwest", "Minnesota", "Northeast", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
      },
      {
        lender_id: 43,
        name: "Orlando Sunshine Capital",
        asset_types: ["Hospitality", "Senior Housing", "Retail", "Land"],
        deal_types: ["Bridge", "Development", "Refinance"],
        capital_types: ["Equity", "Preferred Equity"],
        min_deal_size: 9500000,
        max_deal_size: 105000000,
        locations: ["Southeast", "Florida", "Sun Belt", "Urban"],
        preference_scope: { asset_types: 0.8, deal_types: 0.9, capital_types: 0.8, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
      },
      {
        lender_id: 44,
        name: "San Francisco Bay Lending",
        asset_types: ["Industrial", "Data Center", "Life Science", "Office"],
        deal_types: ["Development", "Refinance", "Value-Add"],
        capital_types: ["Equity", "Senior Debt"],
        min_deal_size: 22000000,
        max_deal_size: 280000000,
        locations: ["West Coast", "California", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
        match_score: 0.9,
        debt_ranges: ["$100M+"],
      },
      {
        lender_id: 45,
        name: "Miami Beach Finance",
        asset_types: ["Hospitality", "Retail", "Office", "Mixed-Use"],
        deal_types: ["Bridge", "Value-Add", "Refinance"],
        capital_types: ["Senior Debt", "Mezzanine"],
        min_deal_size: 7000000,
        max_deal_size: 90000000,
        locations: ["Southeast", "Florida", "Sun Belt", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.9, capital_types: 0.9, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
      },
      {
        lender_id: 46,
        name: "Dallas Skyline Capital",
        asset_types: ["Industrial", "Self-Storage", "Retail", "Multifamily"],
        deal_types: ["Development", "Acquisition", "Bridge"],
        capital_types: ["Equity", "Senior Debt"],
        min_deal_size: 21000000,
        max_deal_size: 260000000,
        locations: ["Southwest", "Texas", "Sun Belt", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
        match_score: 0.9,
        debt_ranges: ["$100M+"],
      },
      {
        lender_id: 47,
        name: "New York City Funding Group",
        asset_types: ["Multifamily", "Office", "Retail", "Mixed-Use"],
        deal_types: ["Acquisition", "Refinance", "Value-Add"],
        capital_types: ["Senior Debt", "Mezzanine"],
        min_deal_size: 5000000,
        max_deal_size: 100000000,
        locations: ["Northeast", "Tri-State Area", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.7 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
      },
      {
        lender_id: 48,
        name: "Los Angeles Property Lending",
        asset_types: ["Hospitality", "Retail", "Office", "Medical Office"],
        deal_types: ["Bridge", "Acquisition", "Repositioning"],
        capital_types: ["Preferred Equity", "Equity"],
        min_deal_size: 15000000,
        max_deal_size: 150000000,
        locations: ["West Coast", "California", "Urban"],
        preference_scope: { asset_types: 0.8, deal_types: 0.9, capital_types: 0.8, locations: 0.9, deal_size: 0.8 },
        match_score: 0.8,
        debt_ranges: ["$100M+"],
      },
      {
        lender_id: 49,
        name: "Chicago Commercial Capital",
        asset_types: ["Industrial", "Data Center", "Multifamily", "Mixed-Use"],
        deal_types: ["Development", "Refinance", "Acquisition"],
        capital_types: ["Equity", "Senior Debt"],
        min_deal_size: 20000000,
        max_deal_size: 250000000,
        locations: ["Midwest", "Illinois", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.8, capital_types: 0.9, locations: 0.9, deal_size: 0.9 },
        match_score: 0.9,
        debt_ranges: ["$100M+"],
      },
      {
        lender_id: 50,
        name: "Houston Energy Corridor Lending",
        asset_types: ["Office", "Industrial", "Data Center", "Mixed-Use"],
        deal_types: ["Refinance", "Value-Add", "Repositioning"],
        capital_types: ["Senior Debt", "Mezzanine"],
        min_deal_size: 7500000,
        max_deal_size: 85000000,
        locations: ["Southwest", "Texas", "Sun Belt", "Urban"],
        preference_scope: { asset_types: 0.9, deal_types: 0.7, capital_types: 0.8, locations: 0.9, deal_size: 0.7 },
        match_score: 0.8,
        debt_ranges: ["$25M - $100M"],
    },
  ];

  return mockLenders;
};